function listItemResource(table) {
  return {
    table,
    listFields: ["id", "package_id", "item"],
    writableFields: ["package_id", "item"],
    searchableFields: ["item"],
    publicList: true,
    publicGet: true,
    publicCreate: false,
  };
}

const resources = {
  users: {
    table: "users",
    listFields: ["id", "first_name", "last_name", "email", "phone", "role", "profile_image", "status", "created_at"],
    writableFields: ["first_name", "last_name", "email", "phone", "password", "role", "profile_image", "status"],
    searchableFields: ["first_name", "last_name", "email", "phone"],
    publicList: false,
    publicGet: false,
    publicCreate: false,
    adminOnlyRead: true,
  },
  vendors: {
    table: "vendors",
    listFields: [
      "id",
      "user_id",
      "business_name",
      "business_phone",
      "business_email",
      "business_address",
      "rib_certificate",
      "approval_status",
      "review_notes",
      "reviewed_by",
      "reviewed_at",
      "created_at",
    ],
    writableFields: [
      "user_id",
      "business_name",
      "business_phone",
      "business_email",
      "business_address",
      "rib_certificate",
      "approval_status",
      "review_notes",
      "reviewed_by",
      "reviewed_at",
    ],
    searchableFields: ["business_name", "business_email", "business_phone"],
    publicList: false,
    publicGet: false,
    publicCreate: false,
    adminOnlyRead: true,
  },
  package_durations: {
    table: "package_durations",
    listFields: ["id", "title", "total_days", "status", "created_at"],
    writableFields: ["title", "total_days", "status"],
    searchableFields: ["title"],
    publicList: true,
    publicGet: true,
    publicCreate: false,
    publicStatusField: "status",
    publicStatus: "active",
  },
  packages: {
    table: "packages",
    listFields: [
      "id",
      "title",
      "slug",
      "short_description",
      "price_per_person",
      "currency",
      "duration_id",
      "main_image",
      "meeting_point",
      "emergency_contact",
      "age_range",
      "fitness_level",
      "status",
      "created_by",
      "vendor_id",
      "created_at",
    ],
    writableFields: [
      "title",
      "slug",
      "short_description",
      "full_description",
      "price_per_person",
      "currency",
      "duration_id",
      "main_image",
      "meeting_point",
      "emergency_contact",
      "age_range",
      "fitness_level",
      "cancellation_policy",
      "status",
      "created_by",
      "vendor_id",
    ],
    searchableFields: ["title", "short_description", "meeting_point"],
    publicList: true,
    publicGet: true,
    publicCreate: false,
    publicStatusField: "status",
    publicStatus: "published",
    vendorOwned: true,
  },
  categories: {
    table: "categories",
    listFields: ["id", "name", "slug", "status", "created_at"],
    writableFields: ["name", "slug", "status"],
    searchableFields: ["name", "slug"],
    publicList: true,
    publicGet: true,
    publicCreate: false,
    publicStatusField: "status",
    publicStatus: "active",
  },
  package_days: {
    table: "package_days",
    listFields: ["id", "package_id", "day_number", "title", "summary", "accommodation", "meals", "start_time", "end_time", "created_at"],
    writableFields: ["package_id", "day_number", "title", "summary", "accommodation", "meals", "start_time", "end_time"],
    searchableFields: ["title", "summary"],
    publicList: true,
    publicGet: true,
    publicCreate: false,
    publicStatusField: "status",
    publicStatus: "active",
  },
  destinations: {
    table: "destinations",
    listFields: [
      "id",
      "name",
      "slug",
      "province",
      "district",
      "category",
      "short_description",
      "best_time_to_visit",
      "entry_fee",
      "latitude",
      "longitude",
      "main_image",
      "status",
      "vendor_id",
      "created_at",
    ],
    writableFields: [
      "name",
      "slug",
      "province",
      "district",
      "category",
      "short_description",
      "full_description",
      "best_time_to_visit",
      "entry_fee",
      "latitude",
      "longitude",
      "main_image",
      "status",
      "vendor_id",
    ],
    searchableFields: ["name", "province", "district", "category", "short_description"],
    publicList: true,
    publicGet: true,
    publicCreate: false,
    publicStatusField: "status",
    publicStatus: "active",
    vendorOwned: true,
  },
  package_day_destinations: {
    table: "package_day_destinations",
    listFields: ["id", "package_day_id", "destination_id", "visit_order", "activity_title", "activity_description", "arrival_time", "departure_time", "notes", "created_at"],
    writableFields: ["package_day_id", "destination_id", "visit_order", "activity_title", "activity_description", "arrival_time", "departure_time", "notes"],
    searchableFields: ["activity_title", "activity_description"],
    publicList: true,
    publicGet: true,
    publicCreate: false,
  },
  package_inclusions: listItemResource("package_inclusions"),
  package_exclusions: listItemResource("package_exclusions"),
  package_required_items: listItemResource("package_required_items"),
  package_not_allowed_items: listItemResource("package_not_allowed_items"),
  package_availability: {
    table: "package_availability",
    listFields: ["id", "package_id", "start_date", "end_date", "total_seats", "reserved_seats", "confirmed_seats", "booking_cutoff_hours", "remaining_seats", "status", "created_at"],
    writableFields: ["package_id", "start_date", "end_date", "total_seats", "reserved_seats", "confirmed_seats", "booking_cutoff_hours", "status"],
    searchableFields: ["status"],
    publicList: true,
    publicGet: true,
    publicCreate: false,
    publicStatusField: "status",
    publicStatus: "available",
  },
  bookings: {
    table: "bookings",
    listFields: ["id", "booking_reference", "user_id", "package_id", "availability_id", "total_people", "total_amount", "special_request", "booking_type", "vip_request_details", "vip_contact_name", "vip_contact_email", "vip_contact_phone", "vip_preferred_contact", "quoted_amount", "quoted_currency", "booking_status", "payment_status", "booked_at"],
    writableFields: ["booking_reference", "user_id", "package_id", "availability_id", "total_people", "total_amount", "special_request", "booking_type", "vip_request_details", "vip_contact_name", "vip_contact_email", "vip_contact_phone", "vip_preferred_contact", "quoted_amount", "quoted_currency", "booking_status", "payment_status"],
    searchableFields: ["booking_reference", "booking_status", "payment_status"],
    publicList: false,
    publicGet: false,
    publicCreate: false,
    ownerField: "user_id",
  },
  booking_participants: {
    table: "booking_participants",
    listFields: ["id", "booking_id", "first_name", "last_name", "gender", "date_of_birth", "passport_number", "nationality", "emergency_contact"],
    writableFields: ["booking_id", "first_name", "last_name", "gender", "date_of_birth", "passport_number", "nationality", "emergency_contact"],
    searchableFields: ["first_name", "last_name", "passport_number", "nationality"],
    publicList: false,
    publicGet: false,
    publicCreate: false,
    adminOnlyRead: true,
  },
  payments: {
    table: "payments",
    listFields: ["id", "booking_id", "amount", "payment_method", "transaction_reference", "payment_proof", "payment_status", "paid_at", "created_at"],
    writableFields: ["booking_id", "amount", "payment_method", "transaction_reference", "payment_proof", "payment_status", "paid_at"],
    searchableFields: ["transaction_reference", "payment_method", "payment_status"],
    publicList: false,
    publicGet: false,
    publicCreate: false,
    adminOnlyRead: true,
  },
  messages: {
    table: "messages",
    listFields: ["id", "full_name", "email", "subject", "message", "created_at"],
    writableFields: ["full_name", "email", "subject", "message"],
    searchableFields: ["full_name", "email", "subject"],
    publicList: false,
    publicGet: false,
    publicCreate: true,
  },
  media_files: {
    table: "media_files",
    listFields: ["id", "file_name", "file_path", "file_type", "uploaded_by", "created_at"],
    writableFields: ["file_name", "file_path", "file_type", "uploaded_by"],
    searchableFields: ["file_name", "file_type"],
    publicList: false,
    publicGet: false,
    publicCreate: false,
    adminOnlyRead: true,
  },
};

module.exports = resources;
