function listItemResource(table) {
  return {
    table,
    listFields: ["id", "package_id", "item"],
    writableFields: ["package_id", "item"],
    searchableFields: ["item"],
    publicList: true,
    publicGet: true,
    publicCreate: false,
  };
}

const resources = {
  users: {
    table: "users",
    listFields: ["id", "first_name", "last_name", "email", "phone", "role", "profile_image", "status", "created_at"],
    writableFields: ["first_name", "last_name", "email", "phone", "password", "role", "profile_image", "status"],
    searchableFields: ["first_name", "last_name", "email", "phone"],
    publicList: false,
    publicGet: false,
    publicCreate: false,
    adminOnlyRead: true,
  },
  vendors: {
    table: "vendors",
    listFields: [
      "id",
      "user_id",
      "business_name",
      "business_phone",
      "business_email",
      "business_address",
      "business_type",
      "registration_number",
      "description",
      "logo",
      "rdb_certificate",
      "approval_status",
      "review_notes",
      "reviewed_by",
      "reviewed_at",
      "created_at",
    ],
    writableFields: [
      "user_id",
      "business_name",
      "business_phone",
      "business_email",
      "business_address",
      "business_type",
      "registration_number",
      "description",
      "logo",
      "rdb_certificate",
      "approval_status",
      "review_notes",
      "reviewed_by",
      "reviewed_at",
    ],
    searchableFields: ["business_name", "business_email", "business_phone"],
    publicList: false,
    publicGet: false,
    publicCreate: false,
    adminOnlyRead: true,
  },
  children: {
    table: "children",
    listFields: ["id", "user_id", "first_name", "last_name", "age", "gender", "medical_notes", "dietary_requirements", "accessibility_requirements", "status", "created_at"],
    writableFields: ["user_id", "first_name", "last_name", "age", "gender", "medical_notes", "dietary_requirements", "accessibility_requirements", "status"],
    searchableFields: ["first_name", "last_name", "status"],
    publicList: false,
    publicGet: false,
    publicCreate: false,
    ownerField: "user_id",
  },
  package_durations: {
    table: "package_durations",
    listFields: ["id", "title", "total_days", "status", "created_at"],
    writableFields: ["title", "total_days", "status"],
    searchableFields: ["title"],
    publicList: true,
    publicGet: true,
    publicCreate: false,
    publicStatusField: "status",
    publicStatus: "active",
  },
  packages: {
    table: "packages",
    listFields: [
      "id",
      "title",
      "slug",
      "short_description",
      "price_per_person",
      "currency",
      "duration_id",
      "main_image",
      "meeting_point",
      "location_name",
      "location_address",
      "minimum_age",
      "maximum_age",
      "minimum_participants",
      "maximum_participants",
      "check_in_time",
      "start_time",
      "end_time",
      "dropoff_location",
      "dropoff_latitude",
      "dropoff_longitude",
      "dropoff_time",
      "dropoff_contact_name",
      "dropoff_contact_phone",
      "dropoff_instructions",
      "pickup_location",
      "pickup_latitude",
      "pickup_longitude",
      "pickup_time",
      "pickup_contact_name",
      "pickup_contact_phone",
      "pickup_instructions",
      "transportation_included",
      "transportation_provider",
      "vehicle_type",
      "departure_point",
      "departure_time",
      "return_time",
      "supervision_details",
      "safety_measures",
      "insurance_details",
      "emergency_contact",
      "age_range",
      "fitness_level",
      "status",
      "approval_status",
      "approval_notes",
      "approved_by",
      "approved_at",
      "created_by",
      "vendor_id",
      "created_at",
    ],
    writableFields: [
      "title",
      "slug",
      "short_description",
      "full_description",
      "price_per_person",
      "currency",
      "duration_id",
      "main_image",
      "meeting_point",
      "location_name",
      "location_address",
      "minimum_age",
      "maximum_age",
      "minimum_participants",
      "maximum_participants",
      "check_in_time",
      "start_time",
      "end_time",
      "dropoff_location",
      "dropoff_latitude",
      "dropoff_longitude",
      "dropoff_time",
      "dropoff_contact_name",
      "dropoff_contact_phone",
      "dropoff_instructions",
      "pickup_location",
      "pickup_latitude",
      "pickup_longitude",
      "pickup_time",
      "pickup_contact_name",
      "pickup_contact_phone",
      "pickup_instructions",
      "transportation_included",
      "transportation_provider",
      "vehicle_type",
      "departure_point",
      "departure_time",
      "return_time",
      "supervision_details",
      "safety_measures",
      "insurance_details",
      "emergency_contact",
      "age_range",
      "fitness_level",
      "cancellation_policy",
      "status",
      "approval_status",
      "approval_notes",
      "approved_by",
      "approved_at",
      "created_by",
      "vendor_id",
    ],
    searchableFields: ["title", "short_description", "meeting_point", "location_name", "location_address"],
    publicList: true,
    publicGet: true,
    publicCreate: false,
    publicStatusField: "status",
    publicStatus: "published",
    vendorOwned: true,
  },
  categories: {
    table: "categories",
    listFields: ["id", "name", "slug", "status", "created_at"],
    writableFields: ["name", "slug", "status"],
    searchableFields: ["name", "slug"],
    publicList: true,
    publicGet: true,
    publicCreate: false,
    publicStatusField: "status",
    publicStatus: "active",
  },
  package_days: {
    table: "package_days",
    listFields: ["id", "package_id", "day_number", "title", "summary", "accommodation", "meals", "location_name", "latitude", "longitude", "start_time", "end_time", "created_at"],
    writableFields: ["package_id", "day_number", "title", "summary", "accommodation", "meals", "location_name", "latitude", "longitude", "start_time", "end_time"],
    searchableFields: ["title", "summary"],
    publicList: true,
    publicGet: true,
    publicCreate: false,
    publicStatusField: "status",
    publicStatus: "active",
  },
  destinations: {
    table: "destinations",
    listFields: [
      "id",
      "name",
      "slug",
      "province",
      "district",
      "category",
      "description",
      "best_time_to_visit",
      "entry_fee",
      "latitude",
      "longitude",
      "main_image",
      "status",
      "vendor_id",
      "created_at",
    ],
    writableFields: [
      "name",
      "slug",
      "province",
      "district",
      "category",
      "description",
      "best_time_to_visit",
      "entry_fee",
      "latitude",
      "longitude",
      "main_image",
      "status",
      "vendor_id",
    ],
    searchableFields: ["name", "province", "district", "category", "description"],
    publicList: true,
    publicGet: true,
    publicCreate: false,
    publicStatusField: "status",
    publicStatus: "active",
    vendorOwned: true,
  },
  package_day_destinations: {
    table: "package_day_destinations",
    listFields: ["id", "package_day_id", "destination_id", "visit_order", "activity_title", "activity_description", "location_name", "latitude", "longitude", "arrival_time", "departure_time", "notes", "created_at"],
    writableFields: ["package_day_id", "destination_id", "visit_order", "activity_title", "activity_description", "location_name", "latitude", "longitude", "arrival_time", "departure_time", "notes"],
    searchableFields: ["activity_title", "activity_description", "location_name"],
    publicList: true,
    publicGet: true,
    publicCreate: false,
  },
  package_inclusions: listItemResource("package_inclusions"),
  package_exclusions: listItemResource("package_exclusions"),
  package_required_items: listItemResource("package_required_items"),
  package_not_allowed_items: listItemResource("package_not_allowed_items"),
  package_availability: {
    table: "package_availability",
    listFields: ["id", "package_id", "start_date", "end_date", "total_seats", "reserved_seats", "confirmed_seats", "booking_cutoff_hours", "remaining_seats", "operation_status", "status", "created_at"],
    writableFields: ["package_id", "start_date", "end_date", "total_seats", "reserved_seats", "confirmed_seats", "booking_cutoff_hours", "operation_status", "status"],
    searchableFields: ["status"],
    publicList: true,
    publicGet: true,
    publicCreate: false,
    publicStatusField: "status",
    publicStatus: "available",
  },
  bookings: {
    table: "bookings",
    listFields: ["id", "booking_reference", "ticket_number", "ticket_token", "ticket_issued_at", "user_id", "package_id", "availability_id", "total_people", "total_amount", "special_request", "authorized_guardian_name", "authorized_guardian_phone", "parent_notes", "terms_accepted", "notification_channel", "booking_type", "vip_request_details", "vip_contact_name", "vip_contact_email", "vip_contact_phone", "vip_preferred_contact", "quoted_amount", "quoted_currency", "booking_status", "payment_status", "booked_at"],
    writableFields: ["booking_reference", "ticket_number", "ticket_token", "ticket_issued_at", "user_id", "package_id", "availability_id", "total_people", "total_amount", "special_request", "authorized_guardian_name", "authorized_guardian_phone", "parent_notes", "terms_accepted", "notification_channel", "booking_type", "vip_request_details", "vip_contact_name", "vip_contact_email", "vip_contact_phone", "vip_preferred_contact", "quoted_amount", "quoted_currency", "booking_status", "payment_status"],
    searchableFields: ["booking_reference", "booking_status", "payment_status"],
    publicList: false,
    publicGet: false,
    publicCreate: false,
    ownerField: "user_id",
  },
  booking_participants: {
    table: "booking_participants",
    listFields: ["id", "booking_id", "child_id", "first_name", "last_name", "gender", "age", "passport_number", "nationality", "emergency_contact", "emergency_contact_name", "emergency_contact_relationship", "medical_notes", "dietary_requirements", "accessibility_requirements", "special_instructions"],
    writableFields: ["booking_id", "child_id", "first_name", "last_name", "gender", "age", "passport_number", "nationality", "emergency_contact", "emergency_contact_name", "emergency_contact_relationship", "medical_notes", "dietary_requirements", "accessibility_requirements", "special_instructions"],
    searchableFields: ["first_name", "last_name", "passport_number", "nationality"],
    publicList: false,
    publicGet: false,
    publicCreate: false,
    adminOnlyRead: true,
  },
  booking_updates: {
    table: "booking_updates",
    listFields: ["id", "booking_id", "availability_id", "package_id", "user_id", "update_type", "title", "message", "sent_channel", "created_by", "created_at"],
    writableFields: ["booking_id", "availability_id", "package_id", "user_id", "update_type", "title", "message", "sent_channel", "created_by"],
    searchableFields: ["update_type", "title", "message"],
    publicList: false,
    publicGet: false,
    publicCreate: false,
    ownerField: "user_id",
  },
  payments: {
    table: "payments",
    listFields: ["id", "booking_id", "amount", "payment_method", "transaction_reference", "payment_proof", "payment_status", "paid_at", "created_at"],
    writableFields: ["booking_id", "amount", "payment_method", "transaction_reference", "payment_proof", "payment_status", "paid_at"],
    searchableFields: ["transaction_reference", "payment_method", "payment_status"],
    publicList: false,
    publicGet: false,
    publicCreate: false,
    adminOnlyRead: true,
  },
  messages: {
    table: "messages",
    listFields: ["id", "full_name", "email", "subject", "message", "created_at"],
    writableFields: ["full_name", "email", "subject", "message"],
    searchableFields: ["full_name", "email", "subject"],
    publicList: false,
    publicGet: false,
    publicCreate: true,
  },
  media_files: {
    table: "media_files",
    listFields: ["id", "file_name", "file_path", "file_type", "uploaded_by", "created_at"],
    writableFields: ["file_name", "file_path", "file_type", "uploaded_by"],
    searchableFields: ["file_name", "file_type"],
    publicList: false,
    publicGet: false,
    publicCreate: false,
    adminOnlyRead: true,
  },
  newsletter_subscribers: {
    table: "newsletter_subscribers",
    listFields: ["id", "email", "user_id", "status", "subscribed_at", "unsubscribed_at"],
    writableFields: ["email", "user_id", "status"],
    searchableFields: ["email", "status"],
    publicList: false,
    publicGet: false,
    publicCreate: true,
    adminOnlyRead: true,
  },
};

module.exports = resources;
